on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://juuusto: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@github.com/Teekkarius-150/teekkarius.fi"
          source_branch: "main"
          destination_repo: "https://juuusto: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@github.com/juuusto/teekkarius.fi"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
